// Worker configuration types
// This file is generated by Wrangler but we define it here for TypeScript compilation

interface Env {
  // Add your environment variables here
  // Example: DATABASE_URL: string;
}

export {};

