import { Hono } from "hono";

// Worker environment type (generated by Wrangler)
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface Env {
  // Add your environment variables here
}

const app = new Hono<{ Bindings: Env }>();

export default app;
