import { Hono } from "hono";

// Worker environment type (generated by Wrangler)
interface Env {
  // Add your environment variables here
}

const app = new Hono<{ Bindings: Env }>();

export default app;
